package corbaNorme;

/**
* corbaNorme/VecteurInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Norme.idl
* mercredi 23 décembre 2020 12 h 22 WEST
*/

public final class VecteurInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaNorme.VecteurInterface value = null;

  public VecteurInterfaceHolder ()
  {
  }

  public VecteurInterfaceHolder (corbaNorme.VecteurInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaNorme.VecteurInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaNorme.VecteurInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaNorme.VecteurInterfaceHelper.type ();
  }

}
