package corbaNorme;


/**
* corbaNorme/VecteurInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Norme.idl
* mercredi 23 décembre 2020 12 h 22 WEST
*/

public interface VecteurInterfaceOperations 
{
  double norme (double a, double b, double c);
} // interface VecteurInterfaceOperations
