package corbaNorme;


/**
* corbaNorme/VecteurInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Norme.idl
* mercredi 23 décembre 2020 12 h 22 WEST
*/

public interface VecteurInterface extends VecteurInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface VecteurInterface
